### ISSUE TITLE
The file is empty!

### ISSUE THREAD

**Issue by xinli2008** [ethan5437/PR-VIST#1]
Good Job!!!!! thank you!
I am trying to reproduce your project,when i want to use your pre-trained storyline predictor model checkpoint,the file seems empty! @ethan5437

**Comment by shaoniana1997** [comment]
And if i bash download_example.sh to use your predicted storylines ,does it mean i can skip STAGE 1: Story Plotting?

**Comment by ethan5437** [comment]
Hi sorry for the late reply, and yes, you can skip STAGE 1.
